Stat svc
IPilin/java-explore-with-me pull request #3
Opened 2023-03-16 21:24 UTC by IPilin

2023-03-17 16:08 UTC, EugeneLenkevich requested changes
Привет, Алексей, спасибо за PR

Все гут, совсем небольшие моменты :)

2023-03-17 16:08 UTC, EugeneLenkevich commented on stat/stat-client/src/test/java/StatsClientTest.java
> +    @SneakyThrows
@SneakyThrows

А зачем тут прятать исключения? 
Мне каежся пусть печатает стэктресы если что то упало  :)

2023-03-17 16:08 UTC, EugeneLenkevich commented on stat/stat-dto/src/main/java/ru/practicum/stat/HitConverter.java
> +    ModelMapper mapper;
private лучше не забывать :)

2023-03-17 16:08 UTC, EugeneLenkevich commented on stat/stat-server/src/main/java/ru/practicum/stat/controller/StatController.java
> +                                         @RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")LocalDateTime end,
Давай попробуем настроить фоматы даты и времени глобально, чтобы не приходилось вот так везде аннотациями это указывать :)

https://www.baeldung.com/spring-boot-formatting-json-dates

2023-03-17 17:16 UTC, IPilin commented on stat/stat-server/src/main/java/ru/practicum/stat/controller/StatController.java
> +                                         @RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")LocalDateTime end,
В результате помогла вот эта статья. Не про spring boot а про spring
https://www.baeldung.com/spring-date-parameters

2023-03-17 19:17 UTC, EugeneLenkevich commented on stat/stat-server/src/main/java/ru/practicum/stat/controller/StatController.java
> +                                         @RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")LocalDateTime end,
Супер что получилось. boot - это всего лишь преднастроенный spring :)

2023-03-18 03:38 UTC, EugeneLenkevich approved these changes
Все супер, спасибо, там оказывается статус задачки не отжался, отправляй закроем ее :)

2023-03-18 13:51 UTC, IPilin commented
> Все супер, спасибо, там оказывается статус задачки не отжался, отправляй закроем ее :)

Не могу отправить, статус задачи в проверке у ревьювера

2023-03-18 14:55 UTC, EugeneLenkevich approved these changes
Да, что то не то, давай еще раз попробуем заапрувить

2023-03-18 15:26 UTC, merged